server:
  # Serve APIs on /api/ and Static Assets on root URL i.e. /
  rootPath: '/api/*'
  applicationConnectors:
      - type: http
        port: 8080
  adminConnectors:
      - type: http
        port: 8081

recaptcha:
  verificationServerUrl: 'https://www.google.com/recaptcha/api/siteverify'
  apiKey: # Add Recaptcha secret API key
  